### ISSUE TITLE
RPI Cam for face recognition.py

### ISSUE THREAD

**Issue by profbit** [thecodacus/Face-Recognition#1]
can someone pls make a code for facerecognition.py which detects faces using rpi cam?
also, i dont want to have the video showned. i just want to detect if it is registered face or not. thank you!

PS: im struggling all over the past 2 months and still cant figure out how can i :(

i have rpi3 and rpi cam module 2, opencv, numpy, python 3.4

**Comment by TH4NOS** [comment]
`import picamera

# Get a reference to the Raspberry Pi camera.
# If this fails, make sure you have a camera connected to the RPi and that you
# enabled your camera in raspi-config and rebooted first.
camera = picamera.PiCamera()
camera.resolution = (320, 240)
output = np.empty((240, 320, 3), dtype=np.uint8)`



please try this and see

**Comment by thecodacus** [comment]
TH4NOS's answer covered it. Closing the issue
