### ISSUE TITLE
recognizer.save not working

### ISSUE THREAD

**Issue by chungyau97** [thecodacus/Face-Recognition#11]
**'trainer' directory is still empty**
**Using 'recognizer = cv2.face_LBPHFaceRecognizer()'**
![image](https://user-images.githubusercontent.com/33013947/73705090-e8068d80-472f-11ea-92ee-6e257ded006f.png)

**Can anyone give me some guidance on saving the yml file?**

**Comment by mandjevant** [comment]
If you are not getting any errors, it could be that it's saving it somewhere else. Consider playing around with the save path, see if it returns the desired path.

**Comment by thecodacus** [comment]
use \\ in the path
