### ISSUE TITLE
i am getting this error updating the file which was having issue. can you please help me

### ISSUE THREAD

**Issue by rnkpareek** [thecodacus/Face-Recognition#4]
Traceback (most recent call last):
  File "C:/Users/dell/Desktop/Face-Recognition-master/Face-Recognition-master/trainer.py", line 39, in <module>
    recognizer = cv2.face.LBPHFaceRecognizer_create()
AttributeError: 'module' object has no attribute 'face'

**Comment by jacksonsmith** [comment]
You must execute dataSetGenerator before.

**Comment by rnkpareek** [comment]
Yeah.. iam executing the file in give sequence .
Data generator, trainer and the last one.

**Comment by thecodacus** [comment]
I guess you are using opencv3, you have to install the opencv with contrib. then only you can use the face module in opencv3
