### ISSUE TITLE
trainer.py 

### ISSUE THREAD

**Issue by imkrishnavenkat** [thecodacus/Face-Recognition#5]
i created id:krishna 
and i tried to train the dataset 
error occured [
![capture](https://user-images.githubusercontent.com/34273160/34917940-61dc559e-f972-11e7-9b5b-742bfb03cd2d.PNG)
](url)

**Comment by jacksonsmith** [comment]
I should that id must be numeric.

**Comment by imkrishnavenkat** [comment]
![capture](https://user-images.githubusercontent.com/34273160/34919074-11f496d8-f984-11e7-8970-984789769707.PNG)

**Comment by jacksonsmith** [comment]
did you delete all images on dataSet folder before run training ?

**Comment by imkrishnavenkat** [comment]
no i didn't deleted any

**Comment by imkrishnavenkat** [comment]
i created my face dataset as 591 and 21 images are saved in dataset folder 
the real problem is with trainer program
