### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by imkrishnavenkat** [thecodacus/Face-Recognition#6]
Can we change labels from integer to string type

**Comment by thecodacus** [comment]
open cv recognizers only accept integers as id. but you can create a sql database table to map the names and there corresponding ids, that way you can get the names from the ids

**Comment by viru12** [comment]
virupaksha@virupaksha-Vbox:~/Face-Recognition$ python trainer.py
Traceback (most recent call last):
  File "trainer.py", line 5, in <module>
    recognizer = cv2.createLBPHFaceRecognizer()
AttributeError: 'module' object has no attribute 'createLBPHFaceRecognizer'

**Comment by droidriz** [comment]
^ that can be solved by 
recognizer = cv2.face.LBPHFaceRecognizer_create()
